name: Build Telegram Bot API

on:
  workflow_dispatch: # يسمح بتشغيل البناء يدوياً

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout telegram-bot-api source
      uses: actions/checkout@v4
      with:
        repository: tdlib/telegram-bot-api
        submodules: recursive

    - name: Setup MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=Release -A x64 .

    - name: Build
      run: cmake --build . --target telegram-bot-api --config Release

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: telegram-bot-api-windows
        path: Release/telegram-bot-api.exe
