name: Build Telegram Bot API

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout telegram-bot-api source
      uses: actions/checkout@v4
      with:
        repository: tdlib/telegram-bot-api
        submodules: recursive

    - name: Setup MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install gperf via Chocolatey
      run: choco install gperf -y

    - name: Install zlib via vcpkg
      run: C:\vcpkg\vcpkg install zlib:x64-windows

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -A x64 -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake ..

    - name: Build
      run: cmake --build build --target telegram-bot-api --config Release

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: telegram-bot-api-windows
        path: build/Release/telegram-bot-api.exe
